title: <p align="center"> Prasad Joshi </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="AIML C55">Batch</a> |

  
  <br>   
  I'm learning data science.
  <br>
  </p>



theme: jekyll-theme-minimal
