title: <p align="center"> Prasad Joshi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/pvjoshi19">GitHub</a>
  
  <br>   
  I'm learning Data Science.
  <br>
  </p>



theme: jekyll-theme-minimal
