title: <p align="center"> Prasad Joshi </p>

description:
  <p align="center">
  <br>   
  I'm learning data science.
  <br>

  
  <br>   
  I'm learning data science.
  <br>
  </p>



theme: jekyll-theme-minimal
